# Generated by Django 4.1.7 on 2023-06-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaluser',
            old_name='timezone',
            new_name='time_zone',
        ),
    ]
